-- Disable foreign keys for seeding speed
PRAGMA foreign_keys = OFF;

-- Seed Schools
INSERT INTO schools (id, name, logo_url) VALUES ('OVK', 'Hoërskool Overkruin', 'https://images.example.com/ovk-logo.png') ON CONFLICT DO NOTHING;

-- Seed Sports
INSERT INTO sports (id, name, config_json) VALUES ('rugby', 'Rugby', '{"sport":"Rugby","fields":[{"key":"tackles_made","label":"Tackles Made","type":"counter"},{"key":"tackles_missed","label":"Tackles Missed","type":"counter"},{"key":"carries","label":"Carries","type":"counter"},{"key":"metres_gained","label":"Metres Gained","type":"numeric"},{"key":"errors","label":"Errors","type":"counter"},{"key":"penalties","label":"Penalties","type":"counter"},{"key":"work_rate","label":"Work Rate","type":"rating_1_5"},{"key":"overall_rating","label":"Overall Rating","type":"rating_1_5"}]}') ON CONFLICT DO NOTHING;

-- Seed Coach User
INSERT INTO users (id, school_id, email, password_hash, role, first_name, last_name) VALUES ('USR-COACH-1', 'OVK', 'coach.ross@overkruin.co.za', 'sha256$mockedhash', 'Coach', 'Ross', 'Venter') ON CONFLICT DO NOTHING;

-- Seed Student User
INSERT INTO users (id, school_id, email, password_hash, role, first_name, last_name) VALUES ('USR-STUDENT-1', 'OVK', 'student@overkruin.co.za', 'sha256$mockedhash', 'Student', 'Liam', 'Venter') ON CONFLICT DO NOTHING;

-- Seed Parent User
INSERT INTO users (id, school_id, email, password_hash, role, first_name, last_name) VALUES ('PAR-OVK-001', 'OVK', 'parent@overkruin.co.za', 'sha256$mockedhash', 'Parent', 'Gerrit', 'Venter') ON CONFLICT DO NOTHING;

-- Seed Players
INSERT INTO players (id, school_id, age_group, first_name, last_name, grade, age, position, team, status, parent_name, parent_contact, parent_id, ugroups_active, notes) VALUES ('OVK-U15-001', 'OVK', 'U15', 'Liam', '', NULL, NULL, NULL, NULL, 'Active', NULL, NULL, 'PAR-OVK-001', 0, NULL);
INSERT INTO players (id, school_id, age_group, first_name, last_name, grade, age, position, team, status, parent_name, parent_contact, parent_id, ugroups_active, notes) VALUES ('OVK-U15-002', 'OVK', 'U15', 'Alex', '', NULL, NULL, NULL, NULL, 'Active', NULL, NULL, 'PAR-OVK-002', 0, NULL);
INSERT INTO players (id, school_id, age_group, first_name, last_name, grade, age, position, team, status, parent_name, parent_contact, parent_id, ugroups_active, notes) VALUES ('OVK-U15-003', 'OVK', 'U15', 'Simpixe', 'F', NULL, NULL, NULL, NULL, 'Active', NULL, NULL, 'PAR-OVK-003', 0, NULL);
INSERT INTO players (id, school_id, age_group, first_name, last_name, grade, age, position, team, status, parent_name, parent_contact, parent_id, ugroups_active, notes) VALUES ('OVK-U15-004', 'OVK', 'U15', 'Izaia', '', NULL, NULL, NULL, NULL, 'Active', NULL, NULL, 'PAR-OVK-004', 0, NULL);
INSERT INTO players (id, school_id, age_group, first_name, last_name, grade, age, position, team, status, parent_name, parent_contact, parent_id, ugroups_active, notes) VALUES ('OVK-U15-005', 'OVK', 'U15', 'Lemmer', 'Andre', NULL, NULL, NULL, NULL, 'Active', NULL, NULL, 'PAR-OVK-005', 0, NULL);
INSERT INTO players (id, school_id, age_group, first_name, last_name, grade, age, position, team, status, parent_name, parent_contact, parent_id, ugroups_active, notes) VALUES ('OVK-U15-006', 'OVK', 'U15', 'Phatu', '', NULL, NULL, NULL, NULL, 'Active', NULL, NULL, 'PAR-OVK-006', 0, NULL);
INSERT INTO players (id, school_id, age_group, first_name, last_name, grade, age, position, team, status, parent_name, parent_contact, parent_id, ugroups_active, notes) VALUES ('OVK-U15-007', 'OVK', 'U15', 'Bibi', 'Achuma', NULL, NULL, NULL, NULL, 'Active', NULL, NULL, 'PAR-OVK-007', 0, NULL);
INSERT INTO players (id, school_id, age_group, first_name, last_name, grade, age, position, team, status, parent_name, parent_contact, parent_id, ugroups_active, notes) VALUES ('OVK-U15-008', 'OVK', 'U15', 'Kyle', 'Smith', NULL, NULL, NULL, NULL, 'Active', NULL, NULL, 'PAR-OVK-008', 0, NULL);
INSERT INTO players (id, school_id, age_group, first_name, last_name, grade, age, position, team, status, parent_name, parent_contact, parent_id, ugroups_active, notes) VALUES ('OVK-U15-009', 'OVK', 'U15', 'Simposhile', 'Masemola', NULL, NULL, NULL, NULL, 'Active', NULL, NULL, 'PAR-OVK-009', 0, NULL);
INSERT INTO players (id, school_id, age_group, first_name, last_name, grade, age, position, team, status, parent_name, parent_contact, parent_id, ugroups_active, notes) VALUES ('OVK-U15-010', 'OVK', 'U15', 'Semanga', '', NULL, NULL, NULL, NULL, 'Active', NULL, NULL, 'PAR-OVK-010', 0, NULL);
INSERT INTO players (id, school_id, age_group, first_name, last_name, grade, age, position, team, status, parent_name, parent_contact, parent_id, ugroups_active, notes) VALUES ('OVK-U15-011', 'OVK', 'U15', 'Shaihan', '', NULL, NULL, NULL, NULL, 'Active', NULL, NULL, 'PAR-OVK-011', 0, NULL);
INSERT INTO players (id, school_id, age_group, first_name, last_name, grade, age, position, team, status, parent_name, parent_contact, parent_id, ugroups_active, notes) VALUES ('OVK-U15-012', 'OVK', 'U15', 'Khumo', '', NULL, NULL, NULL, NULL, 'Active', NULL, NULL, 'PAR-OVK-012', 0, NULL);
INSERT INTO players (id, school_id, age_group, first_name, last_name, grade, age, position, team, status, parent_name, parent_contact, parent_id, ugroups_active, notes) VALUES ('OVK-U15-013', 'OVK', 'U15', 'Kalimamba', '', NULL, NULL, NULL, NULL, 'Active', NULL, NULL, 'PAR-OVK-013', 0, NULL);
INSERT INTO players (id, school_id, age_group, first_name, last_name, grade, age, position, team, status, parent_name, parent_contact, parent_id, ugroups_active, notes) VALUES ('OVK-U15-014', 'OVK', 'U15', 'Nhala', '', NULL, NULL, NULL, NULL, 'Active', NULL, NULL, 'PAR-OVK-014', 0, NULL);
INSERT INTO players (id, school_id, age_group, first_name, last_name, grade, age, position, team, status, parent_name, parent_contact, parent_id, ugroups_active, notes) VALUES ('OVK-U15-015', 'OVK', 'U15', 'Luhanda', '', NULL, NULL, NULL, NULL, 'Active', NULL, NULL, 'PAR-OVK-015', 0, NULL);
INSERT INTO players (id, school_id, age_group, first_name, last_name, grade, age, position, team, status, parent_name, parent_contact, parent_id, ugroups_active, notes) VALUES ('OVK-U15-016', 'OVK', 'U15', 'Theodore', '', NULL, NULL, NULL, NULL, 'Active', NULL, NULL, 'PAR-OVK-016', 0, NULL);
INSERT INTO players (id, school_id, age_group, first_name, last_name, grade, age, position, team, status, parent_name, parent_contact, parent_id, ugroups_active, notes) VALUES ('OVK-U15-017', 'OVK', 'U15', 'Sharlton', '', NULL, NULL, NULL, NULL, 'Active', NULL, NULL, 'PAR-OVK-017', 0, NULL);
INSERT INTO players (id, school_id, age_group, first_name, last_name, grade, age, position, team, status, parent_name, parent_contact, parent_id, ugroups_active, notes) VALUES ('OVK-U15-018', 'OVK', 'U15', 'TK', '', NULL, NULL, NULL, NULL, 'Active', NULL, NULL, 'PAR-OVK-018', 0, NULL);
INSERT INTO players (id, school_id, age_group, first_name, last_name, grade, age, position, team, status, parent_name, parent_contact, parent_id, ugroups_active, notes) VALUES ('OVK-U15-019', 'OVK', 'U15', 'Imaneul', '', NULL, NULL, NULL, NULL, 'Active', NULL, NULL, 'PAR-OVK-019', 0, NULL);
INSERT INTO players (id, school_id, age_group, first_name, last_name, grade, age, position, team, status, parent_name, parent_contact, parent_id, ugroups_active, notes) VALUES ('OVK-U15-020', 'OVK', 'U15', 'Taylon', '', NULL, NULL, NULL, NULL, 'Active', NULL, NULL, 'PAR-OVK-020', 0, NULL);
INSERT INTO players (id, school_id, age_group, first_name, last_name, grade, age, position, team, status, parent_name, parent_contact, parent_id, ugroups_active, notes) VALUES ('OVK-U15-021', 'OVK', 'U15', 'Pharel', '', NULL, NULL, NULL, NULL, 'Active', NULL, NULL, 'PAR-OVK-021', 0, NULL);
INSERT INTO players (id, school_id, age_group, first_name, last_name, grade, age, position, team, status, parent_name, parent_contact, parent_id, ugroups_active, notes) VALUES ('OVK-U15-022', 'OVK', 'U15', 'Kodi', '', NULL, NULL, NULL, NULL, 'Active', NULL, NULL, 'PAR-OVK-022', 0, NULL);
INSERT INTO players (id, school_id, age_group, first_name, last_name, grade, age, position, team, status, parent_name, parent_contact, parent_id, ugroups_active, notes) VALUES ('OVK-U15-023', 'OVK', 'U15', 'Rembo', '', NULL, NULL, NULL, NULL, 'Active', NULL, NULL, 'PAR-OVK-023', 0, NULL);
INSERT INTO players (id, school_id, age_group, first_name, last_name, grade, age, position, team, status, parent_name, parent_contact, parent_id, ugroups_active, notes) VALUES ('OVK-U15-024', 'OVK', 'U15', 'Luvani', '', NULL, NULL, NULL, NULL, 'Active', NULL, NULL, 'PAR-OVK-024', 0, NULL);
INSERT INTO players (id, school_id, age_group, first_name, last_name, grade, age, position, team, status, parent_name, parent_contact, parent_id, ugroups_active, notes) VALUES ('OVK-U16-001', 'OVK', 'U16', 'Jikijela', '', NULL, NULL, NULL, NULL, 'Active', NULL, NULL, 'PAR-OVK-025', 0, NULL);
INSERT INTO players (id, school_id, age_group, first_name, last_name, grade, age, position, team, status, parent_name, parent_contact, parent_id, ugroups_active, notes) VALUES ('OVK-U16-002', 'OVK', 'U16', 'Mongani', 'Tulani', NULL, NULL, NULL, NULL, 'Active', NULL, NULL, 'PAR-OVK-026', 0, NULL);
INSERT INTO players (id, school_id, age_group, first_name, last_name, grade, age, position, team, status, parent_name, parent_contact, parent_id, ugroups_active, notes) VALUES ('OVK-U16-003', 'OVK', 'U16', 'Simpiwe', '', NULL, NULL, NULL, NULL, 'Active', NULL, NULL, 'PAR-OVK-027', 0, NULL);
INSERT INTO players (id, school_id, age_group, first_name, last_name, grade, age, position, team, status, parent_name, parent_contact, parent_id, ugroups_active, notes) VALUES ('OVK-U16-004', 'OVK', 'U16', 'Ambeza', '', NULL, NULL, NULL, NULL, 'Active', NULL, NULL, 'PAR-OVK-028', 0, NULL);
INSERT INTO players (id, school_id, age_group, first_name, last_name, grade, age, position, team, status, parent_name, parent_contact, parent_id, ugroups_active, notes) VALUES ('OVK-U16-005', 'OVK', 'U16', 'Happy', '', NULL, NULL, NULL, NULL, 'Active', NULL, NULL, 'PAR-OVK-029', 0, NULL);
INSERT INTO players (id, school_id, age_group, first_name, last_name, grade, age, position, team, status, parent_name, parent_contact, parent_id, ugroups_active, notes) VALUES ('OVK-U16-006', 'OVK', 'U16', 'Rea', '', NULL, NULL, NULL, NULL, 'Active', NULL, NULL, 'PAR-OVK-030', 0, NULL);
INSERT INTO players (id, school_id, age_group, first_name, last_name, grade, age, position, team, status, parent_name, parent_contact, parent_id, ugroups_active, notes) VALUES ('OVK-U14-001', 'OVK', 'U14', 'Aziel', '', NULL, NULL, NULL, NULL, 'Active', NULL, NULL, 'PAR-OVK-031', 0, NULL);
INSERT INTO players (id, school_id, age_group, first_name, last_name, grade, age, position, team, status, parent_name, parent_contact, parent_id, ugroups_active, notes) VALUES ('OVK-U14-002', 'OVK', 'U14', 'Tyral', '', NULL, NULL, NULL, NULL, 'Active', NULL, NULL, 'PAR-OVK-032', 0, NULL);
INSERT INTO players (id, school_id, age_group, first_name, last_name, grade, age, position, team, status, parent_name, parent_contact, parent_id, ugroups_active, notes) VALUES ('OVK-U14-003', 'OVK', 'U14', 'Liam', '', NULL, NULL, NULL, NULL, 'Active', NULL, NULL, 'PAR-OVK-033', 0, NULL);
INSERT INTO players (id, school_id, age_group, first_name, last_name, grade, age, position, team, status, parent_name, parent_contact, parent_id, ugroups_active, notes) VALUES ('OVK-U14-004', 'OVK', 'U14', 'Wikus', '', NULL, NULL, NULL, NULL, 'Active', NULL, NULL, 'PAR-OVK-034', 0, NULL);
INSERT INTO players (id, school_id, age_group, first_name, last_name, grade, age, position, team, status, parent_name, parent_contact, parent_id, ugroups_active, notes) VALUES ('OVK-U14-005', 'OVK', 'U14', 'Heinrich', '', NULL, NULL, NULL, NULL, 'Active', NULL, NULL, 'PAR-OVK-035', 0, NULL);
INSERT INTO players (id, school_id, age_group, first_name, last_name, grade, age, position, team, status, parent_name, parent_contact, parent_id, ugroups_active, notes) VALUES ('OVK-U14-006', 'OVK', 'U14', 'Lihanru', '', NULL, NULL, NULL, NULL, 'Active', NULL, NULL, 'PAR-OVK-036', 0, NULL);
INSERT INTO players (id, school_id, age_group, first_name, last_name, grade, age, position, team, status, parent_name, parent_contact, parent_id, ugroups_active, notes) VALUES ('OVK-U14-007', 'OVK', 'U14', 'JP', '', NULL, NULL, NULL, NULL, 'Active', NULL, NULL, 'PAR-OVK-037', 0, NULL);
INSERT INTO players (id, school_id, age_group, first_name, last_name, grade, age, position, team, status, parent_name, parent_contact, parent_id, ugroups_active, notes) VALUES ('OVK-U14-008', 'OVK', 'U14', 'Mundu', '', NULL, NULL, NULL, NULL, 'Active', NULL, NULL, 'PAR-OVK-038', 0, NULL);
INSERT INTO players (id, school_id, age_group, first_name, last_name, grade, age, position, team, status, parent_name, parent_contact, parent_id, ugroups_active, notes) VALUES ('OVK-U14-009', 'OVK', 'U14', 'Gugu', '', NULL, NULL, NULL, NULL, 'Active', NULL, NULL, 'PAR-OVK-039', 0, NULL);
INSERT INTO players (id, school_id, age_group, first_name, last_name, grade, age, position, team, status, parent_name, parent_contact, parent_id, ugroups_active, notes) VALUES ('OVK-U14-010', 'OVK', 'U14', 'Jordan', '', NULL, NULL, NULL, NULL, 'Active', NULL, NULL, 'PAR-OVK-040', 0, NULL);
INSERT INTO players (id, school_id, age_group, first_name, last_name, grade, age, position, team, status, parent_name, parent_contact, parent_id, ugroups_active, notes) VALUES ('OVK-U14-011', 'OVK', 'U14', 'Katu', '', NULL, NULL, NULL, NULL, 'Active', NULL, NULL, 'PAR-OVK-041', 0, NULL);
INSERT INTO players (id, school_id, age_group, first_name, last_name, grade, age, position, team, status, parent_name, parent_contact, parent_id, ugroups_active, notes) VALUES ('OVK-U14-012', 'OVK', 'U14', 'Rafa', '', NULL, NULL, NULL, NULL, 'Active', NULL, NULL, 'PAR-OVK-042', 0, NULL);
INSERT INTO players (id, school_id, age_group, first_name, last_name, grade, age, position, team, status, parent_name, parent_contact, parent_id, ugroups_active, notes) VALUES ('OVK-U14-013', 'OVK', 'U14', 'Andre', '', NULL, NULL, NULL, NULL, 'Active', NULL, NULL, 'PAR-OVK-043', 0, NULL);
INSERT INTO players (id, school_id, age_group, first_name, last_name, grade, age, position, team, status, parent_name, parent_contact, parent_id, ugroups_active, notes) VALUES ('OVK-U14-014', 'OVK', 'U14', 'Mothale', '', NULL, NULL, NULL, NULL, 'Active', NULL, NULL, 'PAR-OVK-044', 0, NULL);
INSERT INTO players (id, school_id, age_group, first_name, last_name, grade, age, position, team, status, parent_name, parent_contact, parent_id, ugroups_active, notes) VALUES ('OVK-U14-015', 'OVK', 'U14', 'Katleho', '', NULL, NULL, NULL, NULL, 'Active', NULL, NULL, 'PAR-OVK-045', 0, NULL);
INSERT INTO players (id, school_id, age_group, first_name, last_name, grade, age, position, team, status, parent_name, parent_contact, parent_id, ugroups_active, notes) VALUES ('OVK-U14-016', 'OVK', 'U14', 'Leaho', '', NULL, NULL, NULL, NULL, 'Active', NULL, NULL, 'PAR-OVK-046', 0, NULL);
INSERT INTO players (id, school_id, age_group, first_name, last_name, grade, age, position, team, status, parent_name, parent_contact, parent_id, ugroups_active, notes) VALUES ('OVK-U14-017', 'OVK', 'U14', 'Kyran', '', NULL, NULL, NULL, NULL, 'Active', NULL, NULL, 'PAR-OVK-047', 0, NULL);
INSERT INTO players (id, school_id, age_group, first_name, last_name, grade, age, position, team, status, parent_name, parent_contact, parent_id, ugroups_active, notes) VALUES ('OVK-U14-018', 'OVK', 'U14', 'Tando', '', NULL, NULL, NULL, NULL, 'Active', NULL, NULL, 'PAR-OVK-048', 0, NULL);
INSERT INTO players (id, school_id, age_group, first_name, last_name, grade, age, position, team, status, parent_name, parent_contact, parent_id, ugroups_active, notes) VALUES ('OVK-U14-019', 'OVK', 'U14', 'Lello', '', NULL, NULL, NULL, NULL, 'Active', NULL, NULL, 'PAR-OVK-049', 0, NULL);
INSERT INTO players (id, school_id, age_group, first_name, last_name, grade, age, position, team, status, parent_name, parent_contact, parent_id, ugroups_active, notes) VALUES ('OVK-U14-020', 'OVK', 'U14', 'Kogsi', '', NULL, NULL, NULL, NULL, 'Active', NULL, NULL, 'PAR-OVK-050', 0, NULL);
INSERT INTO players (id, school_id, age_group, first_name, last_name, grade, age, position, team, status, parent_name, parent_contact, parent_id, ugroups_active, notes) VALUES ('OVK-U14-021', 'OVK', 'U14', 'Alamien', '', NULL, NULL, NULL, NULL, 'Active', NULL, NULL, 'PAR-OVK-051', 0, NULL);
INSERT INTO players (id, school_id, age_group, first_name, last_name, grade, age, position, team, status, parent_name, parent_contact, parent_id, ugroups_active, notes) VALUES ('OVK-U14-022', 'OVK', 'U14', 'Trey', '', NULL, NULL, NULL, NULL, 'Active', NULL, NULL, 'PAR-OVK-052', 0, NULL);
INSERT INTO players (id, school_id, age_group, first_name, last_name, grade, age, position, team, status, parent_name, parent_contact, parent_id, ugroups_active, notes) VALUES ('OVK-U14-023', 'OVK', 'U14', 'Leandro', '', NULL, NULL, NULL, NULL, 'Active', NULL, NULL, 'PAR-OVK-053', 0, NULL);

-- Link Student User to Player
UPDATE players SET user_id = 'USR-STUDENT-1' WHERE id = 'OVK-U15-001';

-- Seed Fitness Baselines
INSERT INTO fitness_baselines (player_id, speed_40m, speed_60m, broad_jump, push_ups, pull_ups, squats_40kg, vertical_jump, t_test) VALUES ('OVK-U15-001', 5.702, 8.37, 1.96, 25, 5, 29, 2.58, 10.66);
INSERT INTO fitness_baselines (player_id, speed_40m, speed_60m, broad_jump, push_ups, pull_ups, squats_40kg, vertical_jump, t_test) VALUES ('OVK-U15-002', 6.37, 9.52, 1.85, 23, 0, 29, 2.57, 11.83);
INSERT INTO fitness_baselines (player_id, speed_40m, speed_60m, broad_jump, push_ups, pull_ups, squats_40kg, vertical_jump, t_test) VALUES ('OVK-U15-003', 6.62, 9.77, 1.65, 18, 0, 35, 2.52, 12.54);
INSERT INTO fitness_baselines (player_id, speed_40m, speed_60m, broad_jump, push_ups, pull_ups, squats_40kg, vertical_jump, t_test) VALUES ('OVK-U15-004', 6.22, 9.37, 1.76, 10, 1, 34, 2.42, NULL);
INSERT INTO fitness_baselines (player_id, speed_40m, speed_60m, broad_jump, push_ups, pull_ups, squats_40kg, vertical_jump, t_test) VALUES ('OVK-U15-005', 5.44, 7.8, 2.2, NULL, NULL, NULL, NULL, 13.41);
INSERT INTO fitness_baselines (player_id, speed_40m, speed_60m, broad_jump, push_ups, pull_ups, squats_40kg, vertical_jump, t_test) VALUES ('OVK-U15-006', 5.37, 8.03, 2.25, 23, 2, 23, 2.98, 11.56);
INSERT INTO fitness_baselines (player_id, speed_40m, speed_60m, broad_jump, push_ups, pull_ups, squats_40kg, vertical_jump, t_test) VALUES ('OVK-U15-007', 5.49, 8.19, 2.5, NULL, NULL, NULL, NULL, NULL);
INSERT INTO fitness_baselines (player_id, speed_40m, speed_60m, broad_jump, push_ups, pull_ups, squats_40kg, vertical_jump, t_test) VALUES ('OVK-U15-008', 5.41, 7.94, 2.2, NULL, NULL, NULL, NULL, NULL);
INSERT INTO fitness_baselines (player_id, speed_40m, speed_60m, broad_jump, push_ups, pull_ups, squats_40kg, vertical_jump, t_test) VALUES ('OVK-U15-009', 6.58, 9.56, 1.57, NULL, NULL, NULL, NULL, NULL);
INSERT INTO fitness_baselines (player_id, speed_40m, speed_60m, broad_jump, push_ups, pull_ups, squats_40kg, vertical_jump, t_test) VALUES ('OVK-U15-010', 5.28, 7.6, 2.27, NULL, NULL, NULL, NULL, NULL);
INSERT INTO fitness_baselines (player_id, speed_40m, speed_60m, broad_jump, push_ups, pull_ups, squats_40kg, vertical_jump, t_test) VALUES ('OVK-U15-011', 6.24, 9.16, 1.76, 14, 0, 23, 2.6, 12.13);
INSERT INTO fitness_baselines (player_id, speed_40m, speed_60m, broad_jump, push_ups, pull_ups, squats_40kg, vertical_jump, t_test) VALUES ('OVK-U15-012', 6.09, 8.74, 1.6, NULL, NULL, NULL, NULL, NULL);
INSERT INTO fitness_baselines (player_id, speed_40m, speed_60m, broad_jump, push_ups, pull_ups, squats_40kg, vertical_jump, t_test) VALUES ('OVK-U15-013', 5.99, 7.86, 2.38, NULL, NULL, NULL, NULL, NULL);
INSERT INTO fitness_baselines (player_id, speed_40m, speed_60m, broad_jump, push_ups, pull_ups, squats_40kg, vertical_jump, t_test) VALUES ('OVK-U15-014', 5.31, 8.14, 1.97, 30, 9, 27, 2.64, NULL);
INSERT INTO fitness_baselines (player_id, speed_40m, speed_60m, broad_jump, push_ups, pull_ups, squats_40kg, vertical_jump, t_test) VALUES ('OVK-U15-015', 6.5, NULL, 1.73, NULL, NULL, NULL, NULL, NULL);
INSERT INTO fitness_baselines (player_id, speed_40m, speed_60m, broad_jump, push_ups, pull_ups, squats_40kg, vertical_jump, t_test) VALUES ('OVK-U15-016', 6.04, 9.13, 1.75, NULL, NULL, NULL, NULL, NULL);
INSERT INTO fitness_baselines (player_id, speed_40m, speed_60m, broad_jump, push_ups, pull_ups, squats_40kg, vertical_jump, t_test) VALUES ('OVK-U15-017', 5.36, NULL, 2.08, 22, 4, NULL, 2.73, 10.91);
INSERT INTO fitness_baselines (player_id, speed_40m, speed_60m, broad_jump, push_ups, pull_ups, squats_40kg, vertical_jump, t_test) VALUES ('OVK-U15-018', 5.44, 7.9, 2.08, NULL, NULL, NULL, NULL, NULL);
INSERT INTO fitness_baselines (player_id, speed_40m, speed_60m, broad_jump, push_ups, pull_ups, squats_40kg, vertical_jump, t_test) VALUES ('OVK-U15-019', 5.7, NULL, 2.5, 21, 7, 36, 2.61, 10.91);
INSERT INTO fitness_baselines (player_id, speed_40m, speed_60m, broad_jump, push_ups, pull_ups, squats_40kg, vertical_jump, t_test) VALUES ('OVK-U15-020', NULL, NULL, NULL, 21, 4, 35, 2.77, 10.51);
INSERT INTO fitness_baselines (player_id, speed_40m, speed_60m, broad_jump, push_ups, pull_ups, squats_40kg, vertical_jump, t_test) VALUES ('OVK-U15-021', 6.5, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO fitness_baselines (player_id, speed_40m, speed_60m, broad_jump, push_ups, pull_ups, squats_40kg, vertical_jump, t_test) VALUES ('OVK-U15-022', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO fitness_baselines (player_id, speed_40m, speed_60m, broad_jump, push_ups, pull_ups, squats_40kg, vertical_jump, t_test) VALUES ('OVK-U15-023', 5.1, 7.5, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO fitness_baselines (player_id, speed_40m, speed_60m, broad_jump, push_ups, pull_ups, squats_40kg, vertical_jump, t_test) VALUES ('OVK-U15-024', 4.9, NULL, NULL, NULL, NULL, NULL, 2.81, NULL);
INSERT INTO fitness_baselines (player_id, speed_40m, speed_60m, broad_jump, push_ups, pull_ups, squats_40kg, vertical_jump, t_test) VALUES ('OVK-U16-001', 5.3, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO fitness_baselines (player_id, speed_40m, speed_60m, broad_jump, push_ups, pull_ups, squats_40kg, vertical_jump, t_test) VALUES ('OVK-U16-002', 5.34, 7.9, 2.26, 23, 6, 27, 2.8, 10.9);
INSERT INTO fitness_baselines (player_id, speed_40m, speed_60m, broad_jump, push_ups, pull_ups, squats_40kg, vertical_jump, t_test) VALUES ('OVK-U16-003', 5.38, NULL, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO fitness_baselines (player_id, speed_40m, speed_60m, broad_jump, push_ups, pull_ups, squats_40kg, vertical_jump, t_test) VALUES ('OVK-U16-004', 7.2, 11.05, NULL, 26, 0, 26, 2.45, 12.75);
INSERT INTO fitness_baselines (player_id, speed_40m, speed_60m, broad_jump, push_ups, pull_ups, squats_40kg, vertical_jump, t_test) VALUES ('OVK-U16-005', 5.3, 7.9, NULL, 25, 6, 24, 2.62, 11.02);
INSERT INTO fitness_baselines (player_id, speed_40m, speed_60m, broad_jump, push_ups, pull_ups, squats_40kg, vertical_jump, t_test) VALUES ('OVK-U16-006', 5.5, 8.2, NULL, 31, NULL, NULL, 2.1, NULL);
INSERT INTO fitness_baselines (player_id, speed_40m, speed_60m, broad_jump, push_ups, pull_ups, squats_40kg, vertical_jump, t_test) VALUES ('OVK-U14-001', 5.4, 8.8, NULL, 22, NULL, NULL, 2.77, NULL);
INSERT INTO fitness_baselines (player_id, speed_40m, speed_60m, broad_jump, push_ups, pull_ups, squats_40kg, vertical_jump, t_test) VALUES ('OVK-U14-002', 4.9, 7.3, 2, 3, NULL, NULL, 2.62, NULL);
INSERT INTO fitness_baselines (player_id, speed_40m, speed_60m, broad_jump, push_ups, pull_ups, squats_40kg, vertical_jump, t_test) VALUES ('OVK-U14-003', 5.6, 8.7, 1.9, 24, NULL, NULL, 2.58, NULL);
INSERT INTO fitness_baselines (player_id, speed_40m, speed_60m, broad_jump, push_ups, pull_ups, squats_40kg, vertical_jump, t_test) VALUES ('OVK-U14-004', 5.5, 8.5, 2, 20, NULL, NULL, NULL, NULL);
INSERT INTO fitness_baselines (player_id, speed_40m, speed_60m, broad_jump, push_ups, pull_ups, squats_40kg, vertical_jump, t_test) VALUES ('OVK-U14-005', 5.8, 9.2, 1.7, 27, NULL, NULL, 2.48, NULL);
INSERT INTO fitness_baselines (player_id, speed_40m, speed_60m, broad_jump, push_ups, pull_ups, squats_40kg, vertical_jump, t_test) VALUES ('OVK-U14-006', 5.4, 8.2, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO fitness_baselines (player_id, speed_40m, speed_60m, broad_jump, push_ups, pull_ups, squats_40kg, vertical_jump, t_test) VALUES ('OVK-U14-007', 5.6, 8.6, 1.8, 20, NULL, NULL, 2.45, NULL);
INSERT INTO fitness_baselines (player_id, speed_40m, speed_60m, broad_jump, push_ups, pull_ups, squats_40kg, vertical_jump, t_test) VALUES ('OVK-U14-008', 6.8, 10.9, NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO fitness_baselines (player_id, speed_40m, speed_60m, broad_jump, push_ups, pull_ups, squats_40kg, vertical_jump, t_test) VALUES ('OVK-U14-009', 6.7, 10.71, 1.6, 10, NULL, NULL, NULL, NULL);
INSERT INTO fitness_baselines (player_id, speed_40m, speed_60m, broad_jump, push_ups, pull_ups, squats_40kg, vertical_jump, t_test) VALUES ('OVK-U14-010', 6.4, 10.99, 1.6, 12, NULL, NULL, 2.68, NULL);
INSERT INTO fitness_baselines (player_id, speed_40m, speed_60m, broad_jump, push_ups, pull_ups, squats_40kg, vertical_jump, t_test) VALUES ('OVK-U14-011', 7, 10.8, 1.5, 10, NULL, NULL, NULL, NULL);
INSERT INTO fitness_baselines (player_id, speed_40m, speed_60m, broad_jump, push_ups, pull_ups, squats_40kg, vertical_jump, t_test) VALUES ('OVK-U14-012', 5.4, 8.1, 2, 15, NULL, NULL, 2.73, NULL);
INSERT INTO fitness_baselines (player_id, speed_40m, speed_60m, broad_jump, push_ups, pull_ups, squats_40kg, vertical_jump, t_test) VALUES ('OVK-U14-013', 6.2, 9.6, 1.95, 23, NULL, NULL, 2.57, NULL);
INSERT INTO fitness_baselines (player_id, speed_40m, speed_60m, broad_jump, push_ups, pull_ups, squats_40kg, vertical_jump, t_test) VALUES ('OVK-U14-014', 7.7, 12.4, 0.4, 10, NULL, NULL, 2.31, NULL);
INSERT INTO fitness_baselines (player_id, speed_40m, speed_60m, broad_jump, push_ups, pull_ups, squats_40kg, vertical_jump, t_test) VALUES ('OVK-U14-015', 7.6, 11.5, 1.5, 8, NULL, NULL, 2.58, NULL);
INSERT INTO fitness_baselines (player_id, speed_40m, speed_60m, broad_jump, push_ups, pull_ups, squats_40kg, vertical_jump, t_test) VALUES ('OVK-U14-016', 7.9, 12.43, 1.5, 21, NULL, NULL, 2.48, NULL);
INSERT INTO fitness_baselines (player_id, speed_40m, speed_60m, broad_jump, push_ups, pull_ups, squats_40kg, vertical_jump, t_test) VALUES ('OVK-U14-017', 5.3, 7.4, 2.3, 26, NULL, NULL, 2.81, NULL);
INSERT INTO fitness_baselines (player_id, speed_40m, speed_60m, broad_jump, push_ups, pull_ups, squats_40kg, vertical_jump, t_test) VALUES ('OVK-U14-018', 5.4, 8.2, 1.7, 15, NULL, NULL, 2.53, NULL);
INSERT INTO fitness_baselines (player_id, speed_40m, speed_60m, broad_jump, push_ups, pull_ups, squats_40kg, vertical_jump, t_test) VALUES ('OVK-U14-019', 5.7, 9.3, 1.7, 17, NULL, NULL, 2.64, NULL);
INSERT INTO fitness_baselines (player_id, speed_40m, speed_60m, broad_jump, push_ups, pull_ups, squats_40kg, vertical_jump, t_test) VALUES ('OVK-U14-020', 6.2, 9.6, 1.7, 15, NULL, NULL, 2.51, NULL);
INSERT INTO fitness_baselines (player_id, speed_40m, speed_60m, broad_jump, push_ups, pull_ups, squats_40kg, vertical_jump, t_test) VALUES ('OVK-U14-021', 5.5, 7.8, 2.2, 30, NULL, NULL, 2.91, NULL);
INSERT INTO fitness_baselines (player_id, speed_40m, speed_60m, broad_jump, push_ups, pull_ups, squats_40kg, vertical_jump, t_test) VALUES ('OVK-U14-022', NULL, 8.7, 1.75, 16, NULL, NULL, 2.48, NULL);
INSERT INTO fitness_baselines (player_id, speed_40m, speed_60m, broad_jump, push_ups, pull_ups, squats_40kg, vertical_jump, t_test) VALUES ('OVK-U14-023', 5.3, 8.2, 2, 41, NULL, NULL, 2.48, NULL);

-- Seed Academic Logs

-- Re-enable foreign keys
PRAGMA foreign_keys = ON;
