-- Migration: Seed athlete ages, positions, and teams to match roster UI mockup
UPDATE players SET age = 15, position = 'Flanker', team = 'Academy Elite', age_group = 'U15' WHERE id = 'OVK-U15-001';
UPDATE players SET age = 15, position = 'Flanker / No. 8', team = 'Academy Elite', age_group = 'U15' WHERE id = 'OVK-U15-002';
UPDATE players SET age = 15, position = 'Fly-half', team = 'Academy Elite', age_group = 'U15' WHERE id = 'OVK-U15-003';
UPDATE players SET age = 16, position = 'Hooker', team = 'Academy Elite', age_group = 'U16' WHERE id = 'OVK-U15-004';
UPDATE players SET age = 15, position = 'Fly-half', team = 'Academy Elite', age_group = 'U15' WHERE id = 'OVK-U15-005';
UPDATE players SET age = 15, position = 'Center', team = 'Premier Squad', age_group = 'U15' WHERE id = 'OVK-U15-006';
UPDATE players SET age = 16, position = 'Fly-half', team = 'Academy Elite', age_group = 'U16' WHERE id = 'OVK-U15-007';
UPDATE players SET age = 15, position = 'Full-back', team = 'Academy Elite', age_group = 'U15' WHERE id = 'OVK-U15-008';
UPDATE players SET age = 15, position = 'Lock / Second Row', team = 'Academy Elite', age_group = 'U15' WHERE id = 'OVK-U15-009';
UPDATE players SET age = 15, position = 'Lock', team = 'Development B', age_group = 'U15' WHERE id = 'OVK-U15-010';
UPDATE players SET age = 15, position = 'Flanker', team = 'Academy Elite', age_group = 'U15' WHERE id = 'OVK-U15-011';
UPDATE players SET age = 15, position = 'No. 8', team = 'Premier Squad', age_group = 'U15' WHERE id = 'OVK-U15-012';
UPDATE players SET age = 15, position = 'Scrum-half', team = 'Development B', age_group = 'U15' WHERE id = 'OVK-U15-013';
UPDATE players SET age = 15, position = 'Fly-half', team = 'Academy Elite', age_group = 'U15' WHERE id = 'OVK-U15-014';
UPDATE players SET age = 15, position = 'Center', team = 'Premier Squad', age_group = 'U15' WHERE id = 'OVK-U15-015';
UPDATE players SET age = 15, position = 'Wing', team = 'Development B', age_group = 'U15' WHERE id = 'OVK-U15-016';
UPDATE players SET age = 15, position = 'Full-back', team = 'Academy Elite', age_group = 'U15' WHERE id = 'OVK-U15-017';
UPDATE players SET age = 15, position = 'Prop', team = 'Premier Squad', age_group = 'U15' WHERE id = 'OVK-U15-018';
UPDATE players SET age = 15, position = 'Lock / Second Row', team = 'Academy Elite', age_group = 'U15' WHERE id = 'OVK-U15-019';
UPDATE players SET age = 15, position = 'Flanker', team = 'Academy Elite', age_group = 'U15' WHERE id = 'OVK-U15-020';
UPDATE players SET age = 15, position = 'No. 8', team = 'Premier Squad', age_group = 'U15' WHERE id = 'OVK-U15-021';
UPDATE players SET age = 15, position = 'Scrum-half', team = 'Development B', age_group = 'U15' WHERE id = 'OVK-U15-022';
UPDATE players SET age = 15, position = 'Fly-half', team = 'Academy Elite', age_group = 'U15' WHERE id = 'OVK-U15-023';
UPDATE players SET age = 15, position = 'Center', team = 'Premier Squad', age_group = 'U15' WHERE id = 'OVK-U15-024';
UPDATE players SET age = 16, position = 'Flanker', team = 'Academy Elite', age_group = 'U16' WHERE id = 'OVK-U16-001';
UPDATE players SET age = 16, position = 'No. 8', team = 'Premier Squad', age_group = 'U16' WHERE id = 'OVK-U16-002';
UPDATE players SET age = 16, position = 'Scrum-half', team = 'Development B', age_group = 'U16' WHERE id = 'OVK-U16-003';
UPDATE players SET age = 16, position = 'Fly-half', team = 'Academy Elite', age_group = 'U16' WHERE id = 'OVK-U16-004';
UPDATE players SET age = 16, position = 'Center', team = 'Premier Squad', age_group = 'U16' WHERE id = 'OVK-U16-005';
UPDATE players SET age = 16, position = 'Wing', team = 'Development B', age_group = 'U16' WHERE id = 'OVK-U16-006';
UPDATE players SET age = 18, position = 'Hooker', team = 'Premier Squad', age_group = 'U14' WHERE id = 'OVK-U14-001';
UPDATE players SET age = 18, position = 'Lock', team = 'Development B', age_group = 'U14' WHERE id = 'OVK-U14-002';
UPDATE players SET age = 18, position = 'Flanker', team = 'Academy Elite', age_group = 'U14' WHERE id = 'OVK-U14-003';
UPDATE players SET age = 18, position = 'No. 8', team = 'Premier Squad', age_group = 'U14' WHERE id = 'OVK-U14-004';
UPDATE players SET age = 18, position = 'Scrum-half', team = 'Development B', age_group = 'U14' WHERE id = 'OVK-U14-005';
UPDATE players SET age = 18, position = 'Fly-half', team = 'Academy Elite', age_group = 'U14' WHERE id = 'OVK-U14-006';
UPDATE players SET age = 18, position = 'Center', team = 'Premier Squad', age_group = 'U14' WHERE id = 'OVK-U14-007';
UPDATE players SET age = 18, position = 'Wing', team = 'Development B', age_group = 'U14' WHERE id = 'OVK-U14-008';
UPDATE players SET age = 18, position = 'Full-back', team = 'Academy Elite', age_group = 'U14' WHERE id = 'OVK-U14-009';
UPDATE players SET age = 18, position = 'Hooker', team = 'Premier Squad', age_group = 'U14' WHERE id = 'OVK-U14-010';
UPDATE players SET age = 18, position = 'Lock', team = 'Development B', age_group = 'U14' WHERE id = 'OVK-U14-011';
UPDATE players SET age = 18, position = 'Flanker', team = 'Academy Elite', age_group = 'U14' WHERE id = 'OVK-U14-012';
UPDATE players SET age = 18, position = 'No. 8', team = 'Premier Squad', age_group = 'U14' WHERE id = 'OVK-U14-013';
UPDATE players SET age = 18, position = 'Scrum-half', team = 'Development B', age_group = 'U14' WHERE id = 'OVK-U14-014';
UPDATE players SET age = 18, position = 'Fly-half', team = 'Academy Elite', age_group = 'U14' WHERE id = 'OVK-U14-015';
UPDATE players SET age = 18, position = 'Center', team = 'Premier Squad', age_group = 'U14' WHERE id = 'OVK-U14-016';
UPDATE players SET age = 18, position = 'Wing', team = 'Development B', age_group = 'U14' WHERE id = 'OVK-U14-017';
UPDATE players SET age = 18, position = 'Full-back', team = 'Academy Elite', age_group = 'U14' WHERE id = 'OVK-U14-018';
UPDATE players SET age = 18, position = 'Prop', team = 'Premier Squad', age_group = 'U14' WHERE id = 'OVK-U14-019';
UPDATE players SET age = 18, position = 'Lock', team = 'Development B', age_group = 'U14' WHERE id = 'OVK-U14-020';
UPDATE players SET age = 18, position = 'Flanker', team = 'Academy Elite', age_group = 'U14' WHERE id = 'OVK-U14-021';
UPDATE players SET age = 18, position = 'No. 8', team = 'Premier Squad', age_group = 'U14' WHERE id = 'OVK-U14-022';
UPDATE players SET age = 18, position = 'Scrum-half', team = 'Development B', age_group = 'U14' WHERE id = 'OVK-U14-023';
